### ISSUE TITLE
Ammunition tracking in firearms

### ISSUE THREAD

**Issue by gmmatt** [MetaMorphic-Digital/torgeternity#36]
Abiility to select single, short, long when using firearm. Ability to track ammunition.

- [x] On an attack roll, does the weapon have ammo currently at all?
- [x] Check if the weapon has a sufficient amount of bullets (BURST ATTACK!)
- [x] Reduce the weapon's ammo.value
- [x] On this cause, throw out the bd button on the attack items
- [x] plausibility test if value > max, throw some error
- [x] Resource management with ammunition / item in item?
  - [x] Change the Delete Button (honestly, it can be deleted on the gear tab) to _reload weapon_
- [x] Chatoutput with remaining bullets in the used weapon
- [x] Chatoutput after reloading a weapon

**Comment by pemerson71** [comment]
Ooh... this one is VERY IMPORTANT for GMs, in particular.

**Comment by Algor0113** [comment]
Burst is implemented, track ammunition needs resolve.

**Comment by pemerson71** [comment]
Have either of you heard any complaints or desires to have ammunition tracked on the Character sheet?  I honestly haven't heard a single thing about it.  If we've not heard anything, is it really that important to keep open?

**Comment by Algor0113** [comment]
Somehow implement reload / consumable item / something like that
